on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
jobs:
  src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.9.2
          vessel-version: 0.6.3
      - run: for i in src/*.mo ; do $(vessel bin)/moc $(vessel sources) --check $i ; done
      - run: for i in test/*.mo ; do $(vessel bin)/moc $(vessel sources) -r $i ; done
